<template>
  <div>
  <b-container class="pt-3">
    <b-row>
      <b-col>
        <b-card title="Tecladao da massa"
                img-src="../assets/logo.png"
                img-alt="teclado"
                img-top
                style="max-width: 20rem;"
                class="mb-2">
            <p class="card-text">
              <img src="../assets/logo.png" class="card-img-top">
            tecladao da massa
            </p>
            <b-button href="#" variant="primary">R$ 100,00</b-button>
        </b-card>
      </b-col>

      <b-col>
        <b-card title="Tecladao da massa"
                img-src="../assets/produtos/teclado/teclado-1.jpg"
                img-alt="teclado"
                img-top
                style="max-width: 20rem;"
                class="mb-2">
            <p class="card-text">
            tecladao da massa
            </p>
            <b-button href="#" variant="primary">R$ 100,00</b-button>
        </b-card>
      </b-col>
    
    </b-row>

    <b-row>
      
      <b-col>
        <b-card title="Tecladao da massa"
                img-src="../assets/produtos/teclado/teclado-1.jpg"
                img-alt="teclado"
                img-top
                style="max-width: 20rem;"
                class="mb-2">
            <p class="card-text">
            tecladao da massa
            </p>
            <b-button href="#" variant="primary">R$ 100,00</b-button>
        </b-card>
      </b-col>

      <b-col>
        <b-card title="Tecladao da massa"
                img-src="../assets/produtos/teclado/teclado-1.jpg"
                img-alt="teclado"
                img-top
                style="max-width: 20rem;"
                class="mb-2">
            <p class="card-text">
            tecladao da massa
            </p>
            <b-button href="#" variant="primary">R$ 100,00</b-button>
        </b-card>
      </b-col>
    </b-row>
  </b-container>
  </div>
</template>


<style>

</style>
